### ISSUE TITLE
Inventory update-while-scrolling

### ISSUE THREAD

**Issue by Deeringmw** [mohnjiles/Beast-Android#4]
Inventory initially loads items in an incorrect order and then rectifies itself. Looks like Christmas light flickering.

**Comment by mohnjiles** [comment]
Happens due to asynchronous loading of the images, plus the views being recycled to save memory. Images are loaded from the web and cached on device to keep apk size down.

Also, this happens with most all async image loading libraries on Android that I've seen. (I'm using Glide)

Enjoy your lights!
